defaultEntryPoints = ["http"]
logLevel = "INFO"

[api]

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false
swarmMode = true
watch = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8080"
