---
variables:
  PACKAGE_NAME: 'toggl2pl'
  PACKAGE_VERSION: '1.0.0'

stages:
  - build
  - test

build:linux:
  artifacts:
    paths:
      - ${PACKAGE_NAME}-${PACKAGE_VERSION}-linux
    expire_in: 1 hrs
  before_script:
    - apt update
    - apt install --assume-yes binutils
    - pip install virtualenv
    - virtualenv --python=python3 venv
  image: python:3.7.2-slim-stretch
  script:
    - venv/bin/pip install --upgrade --requirement requirements.txt
    - venv/bin/pyinstaller --distpath . --name ${PACKAGE_NAME}-${PACKAGE_VERSION}-linux --onefile scripts/${PACKAGE_NAME}
  stage: build
  tags:
    - docker
  variables:
    DEBIAN_FRONTEND: noninteractive
