---
dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install --upgrade --requirement requirements.txt
  - pip install --upgrade --requirement tests/requirements.txt
script:
  - coverage run -m pytest
